<h2>Twitter</h2>

<ul>
	<li><a href="/twitter/client">Client</a></li>
</ul>


<h3>Descrição</h3>

<p>
Twitter é uma rede social e servidor para microblogging, que permite aos usuários enviar e receber atualizações pessoais de outros contatos (em textos de até 140 caracteres, conhecidos como "tweets"), por meio do website do serviço, por SMS e por softwares específicos de gerenciamento.
</p>

<ul>
    <li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/Twitter">http://pt.wikipedia.org/wiki/Twitter</a></li>
    <li><strong>Site:</strong> <a href="https://twitter.com/">https://twitter.com/</a></li>
    <li><strong>Site API:</strong> <a href="https://dev.twitter.com/">https://dev.twitter.com/</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.service.twitter.html">http://framework.zend.com/manual/en/zend.service.twitter.html</a></li>
    <li><strong>Código:</strong> <a href=""></a></li>
</ul>

