
<ul>
	<li><a href="/introducao#1">Introdução</a></li>
	<li><a href="/introducao#2">Zend Framework</a></li>
	<li><a href="/introducao#3">O que é um webservice?</a></li>
</ul>


<h2>Protocolos</h2>

<ul>
    <li><a href="/soap">SOAP</a></li>
    <li><a href="/xmlrpc">XML-RPC</a></li>
    <li><a href="/rest">Rest</a></li>
    <li><a href="/json">JSON</a></li>
</ul>

<h2>Feeds</h2>
<ul>
    <li><a href="/rss">RSS</a></li>
    <li><a href="/atom">ATOM</a></li>
</ul>


<h2>API</h2>
<ul>
    <li><a href="/openid">OpenID</a></li>
</ul>


<h2>Serviços</h2>
<ul>
    <li><a href="/twitter">Twitter</a></li>
</ul>

