<h2>Protocolos</h2>
<ul>
    <li><a href="/soap">SOAP</a></li>
    <li><a href="/xmlrpc">XML-RPC</a></li>
    <li><a href="/rest">Rest</a></li>
    <li><a href="/json">JSON</a></li>
</ul>

<h2>Feeds</h2>
<ul>
    <li><a href="/rss">RSS</a></li>
    <li><a href="/atom">ATOM</a></li>
</ul>


<h2>API</h2>
<ul>
    <li><a href="/provider">OPENID - Provider</a></li>
    <li><a href="/consumer">OPENID - Consumer</a></li>
</ul>


