<h2>Rest</h2>

<ul>
	<li><a href="/rest/server">Server</a></li>
	<li><a href="/rest/client">Client</a></li>
</ul>


<h3>Descrição</h3>

<p>
A Transferência de Estado Representacional (Representational State Transfer) ou
somente (REST) é uma técnica de engenharia de software para sistemas hipermídia
distribuídos como a World Wide Web. O termo se originou no ano de 2000, em uma
tese de doutorado (PHD) sobre a web escrita por Roy Fielding, um dos principais
autores da especificação do protocolo HTTP que é utilizado por sites da
internet.
</p>

<ul>
	<li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/REST">http://pt.wikipedia.org/wiki/REST</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.rest.introduction.html">http://framework.zend.com/manual/en/zend.rest.introduction.html</a></li>
    <li><strong>Dissertação do Dr. Roy:</strong> <a href="http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm">http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm</a></li>
    <li><strong>Código:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/application/controllers/RestController.php" target="_blank">github.com</a></li>
</ul>
