<h2>JSON</h2>

<ul>
	<li><a href="/json/server">Server</a></li>
	<li><a href="/json/client">Client</a></li>
</ul>


<h3>Descrição</h3>

<p>
JSON, um acrônimo para "<strong>JavaScript Object Notation</strong>", é um formato leve para
intercâmbio de dados computacionais. JSON é um subconjunto da notação de objeto
de JavaScript, mas seu uso não requer Javascript exclusivamente.
</p>
<p>
O formato JSON foi originalmente criado por Douglas Crockford e é descrito no
<a href="http://tools.ietf.org/html/rfc4627">RFC 4627</a>. O media-type oficial do JSON é application/json e a extensão é .json.
</p>
<p>
A simplicidade de JSON tem resultado em seu uso difundido, especialmente como
uma alternativa para XML em AJAX. Uma das vantagens reivindicadas de JSON sobre
XML como um formato para intercâmbio de dados neste contexto, é o fato de ser
muito mais fácil escrever um analisador JSON. Em JavaScript mesmo, JSON pode ser
analisado trivialmente usando a função eval(). Isto foi importante para a
aceitação de JSON dentro da comunidade AJAX devido a presença deste recurso de
JavaScript em todos os navegadores web atuais.
</p>

<ul>
	<li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/JSON">http://pt.wikipedia.org/wiki/JSON</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.json.introduction.html">http://framework.zend.com/manual/en/zend.json.introduction.html</a></li>
    <li><strong>Especificação:</strong> <a href="http://framework.zend.com/manual/en/zend.json.introduction.html">http://www.json.org/</a></li>
    <li><strong>JQuery.JSON-RPC:</strong> <a href="http://plugins.jquery.com/project/zendjsonrpc">http://plugins.jquery.com/project/zendjsonrpc</a></li>
    <li><strong>Código Controller:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/application/controllers/JsonController.php" target="_blank">github.com</a></li>
    <li><strong>Código JavaScript:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/public/js/json/client.js" target="_blank">github.com</a></li>
</ul>
