<h2>RSS</h2>

<ul>
	<li><a href="/rss/server">Server</a></li>
	<li><a href="/rss/client">Client</a></li>
</ul>


<h3>Descrição</h3>

<p>
RSS é um subconjunto de "dialetos" XML que servem para agregar conteúdo ou "Web
syndication", podendo ser acessado mediante programas ou sites agregadores. É
usado principalmente em sites de notícias e blogs.
</p>

<p>
A abreviatura do RSS é usada para se referir aos seguintes padrões:
</p>

<ul>
	<li>Rich Site Summary (RSS 0.91)</li>
    <li>RDF Site Summary (RSS 0.9 e 1.0)</li>
    <li>Really Simple Syndication (RSS 2.0)</li>
</ul>

<p>
A tecnologia do RSS permite aos usuários da internet se inscreverem em sites que
fornecem "feeds" RSS. Estes são tipicamente sites que mudam ou atualizam o seu
conteúdo regularmente. Para isso, são utilizados Feeds RSS que recebem estas
atualizações, desta maneira o utilizador pode permanecer informado de diversas
atualizações em diversos sites sem precisar visitá-los um a um.
</p>

<p>
Os feeds RSS oferecem conteúdo Web ou resumos de conteúdo juntamente com os
links para as versões completas deste conteúdo e outros metadados. Esta
informação é entregue como um arquivo XML chamado "RSS feed", "webfeed", "Atom"
ou ainda canal RSS.
</p>

<ul>
    <li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/RSS">http://pt.wikipedia.org/wiki/RSS</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.feed.consuming-rss.html">http://framework.zend.com/manual/en/zend.feed.consuming-rss.html</a></li>
    <li><strong>Especificação:</strong> <a href="http://cyber.law.harvard.edu/rss/index.html">http://cyber.law.harvard.edu/rss/index.html</a></li>
    <li><strong>Código:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/application/controllers/RssController.php" target="_blank">github.com</a></li>
</ul>
