<h2>XML-RPC</h2>

<ul>
	<li><a href="/xmlrpc/server">Server</a></li>
	<li><a href="/xmlrpc/client">Client</a></li>
</ul>


<h3>Descrição</h3>

<p>
O XML-RPC é um protocolo de chamada de procedimento remoto (CPR) que utiliza XML
para codificar suas chamadas e HTTP como um mecanismo de transporte. É um
protocolo simples, definido com poucas linhas de códigos em oposição com a
maioria dos sistemas de RPC, onde os documentos padrões são freqüentemente com
milhares de páginas e exige apoio de softwares para serem usados.
</p>

<ul>
    <li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/XML-RPC">http://pt.wikipedia.org/wiki/XML-RPC</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.xmlrpc.html">http://framework.zend.com/manual/en/zend.xmlrpc.html</a></li>
    <li><strong>Especificação:</strong> <a href="http://www.xmlrpc.com/">http://www.xmlrpc.com/</a></li>
    <li><strong>Código:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/application/controllers/XmlrpcController.php" target="_blank">github.com</a></li>
</ul>
