<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Webservices - <?php echo $this->headTitle() ?></title>

    <script src="/js/jquery-1.6.1.min.js"></script>
    <SCRIPT LANGUAGE="javascript" SRC="/js/json2.js"></SCRIPT>
    <SCRIPT LANGUAGE="javascript" SRC="/js/jquery.zend.jsonrpc.js"></SCRIPT>


    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>

</head>
<body>
<h1>Webservices</h1>

<?php
    echo $this->layout()->content;
?>
</body>
</html>
