<h2>SOAP</h2>

<ul>
	<li><a href="/soap/server?wsdl">WSDL</a></li>
	<li><a href="/soap/server">Server</a></li>
	<li><a href="/soap/client">Client</a></li>
</ul>


<h3>Descrição</h3>

<p>
SOAP, originado do acrônimo inglês <strong>Simple Object Access Protocol</strong>, e em português
Protocolo Simples de Acesso a Objetos, é um protocolo para troca de informações
estruturadas em uma plataforma descentralizada e distribuída. Ele se baseia na
Linguagem de Marcação Extensível (XML) para seu formato de mensagem, e
normalmente baseia-se em outros protocolos da Camada de aplicação, mais
notavelmente em Chamada de Procedimento Remoto (RPC) e Protocolo de
Transferência de Hipertexto (HTTP), para negociação e transmissão de mensagens.
SOAP pode formar a camada base de uma pilha de protocolos de web services,
</p>

<ul>
	<li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/SOAP">http://pt.wikipedia.org/wiki/SOAP</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.soap.server.html">http://framework.zend.com/manual/en/zend.soap.server.html</a></li>
    <li><strong>W3C:</strong> <a href="http://www.w3.org/TR/soap/">http://www.w3.org/TR/soap/</a></li>
    <li><strong>Código:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/application/controllers/SoapController.php" target="_blank">github.com</a></li>
</ul>


