<h2>Introdução</h2>

<p>
Web service é uma solução utilizada na integração de sistemas e na comunicação
entre aplicações diferentes. Com esta tecnologia é possível que novas aplicações
possam interagir com aquelas que já existem e que sistemas desenvolvidos em
plataformas diferentes sejam compatíveis. Os Web services são componentes que
permitem às aplicações enviar e receber dados em formato XML. Cada aplicação
pode ter a sua própria "linguagem", que é traduzida para uma linguagem
universal, o formato XML.
</p>

<p>
Para as empresas, os Web services podem trazer agilidade para os processos e
eficiência na comunicação entre cadeias de produção ou de logística. Toda e
qualquer comunicação entre sistemas passa a ser dinâmica e principalmente
segura, pois não há intervenção humana.
</p>

<p>
Essencialmente, o Web Service faz com que os recursos da aplicação do software
estejam disponíveis sobre a rede de uma forma normalizada. Outras tecnologias
fazem a mesma coisa, como por exemplo, os browsers da Internet acedem às páginas
Web disponíveis usando por norma as tecnologias da Internet, HTTP e HTML. No
entanto, estas tecnologias não são bem sucedidas na comunicação e integração de
aplicações. Existe uma grande motivação sobre a tecnologia Web Service pois
possibilita que diferentes aplicações comuniquem entre si e utilizem recursos
diferentes.
</p>

<p>
Utilizando a tecnologia Web Service, uma aplicação pode invocar outra para
efectuar tarefas simples ou complexas mesmo que as duas aplicações estejam em
diferentes sistemas e escritas em linguagens diferentes. Por outras palavras, os
Web Services fazem com que os seus recursos estejam disponíveis para que
qualquer aplicação cliente possa operar e extrair os recursos fornecidos pelo
Web Service.
</p>


<ul>
	<li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/Web_service">http://pt.wikipedia.org/wiki/Web_service</a></li>
</ul>
