<h2 id="1">Introdução</h2>

<p>
Esta apresentação é dedicada a todos os programadores que desejam integrar seus sistemas
com outros.
</p>

<p>
Sendo que a implementação seja diferente de:
<ul>
    <li>importação de arquivos .xls ou .csv.</li>
    <li>leitura de arquivos de lote TXT tabulados.</li>
    <li>xml esquisito.</li>
    <li>copy paste.</li>
</ul>
</p>

<img src="/img/webservice_1.jpg">


<h2 id="2">Zend Framework</h2>

<p>
Nesta apresentação usaremos o Zend Framework para a estudar os protocolos, as APIS e os serviços para ajudar nas nossas implementações.
</p>
<p>
Listagem dos serviços/protocolos/APIs suportados no Zend Framework:
</p>

<ul>
    <li><a href="http://framework.zend.com/manual/en/zend.soap.server.html">SOAP</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.xmlrpc.html">XML-RPC</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.rest.introduction.html">Rest</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.json.introduction.html">JSON</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.feed.consuming-rss.html">RSS</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.feed.consuming-atom.html">Atom</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.openid.introduction.html">OpenId</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.oauth.introduction.html">Oauth</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.twitter.html">Twitter</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.technorati.html">Technorati</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.short-url.html">Short-URL</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.livedocx.html">LiveDocx</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.flickr.html">Flickr</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.delicious.html">Delicious</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.akismet.html">Akismet</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.amazon.ec2.html">Amazon Ec2</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.amazon.s3.html">S3</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.audioscrobbler.html">Audioscrobbler</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.ebay.html">Ebay</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.recaptcha.html">Recaptcha</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.windowsazure.html">Windowsazure</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.yahoo.html">Yahoo</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.service.slideshare.html">Slideshare</a></li>
    <li><a href="http://framework.zend.com/manual/en/zend.gdata.html">Google</a></li>
</ul>



<img src="/img/webservice_2.jpg">



<h2 id="3">O que é um webservice?</h2>
<p>
Web service é uma solução utilizada na integração de sistemas e na comunicação
entre aplicações diferentes. Com esta tecnologia é possível que novas aplicações
possam interagir com aquelas que já existem e que sistemas desenvolvidos em
plataformas diferentes sejam compatíveis. Os Web services são componentes que
permitem às aplicações enviar e receber dados em formato XML. Cada aplicação
pode ter a sua própria "linguagem", que é traduzida para uma linguagem
universal, o formato XML.
</p>

<p>
Para as empresas, os Web services podem trazer agilidade para os processos e
eficiência na comunicação entre cadeias de produção ou de logística. Toda e
qualquer comunicação entre sistemas passa a ser dinâmica e principalmente
segura, pois não há intervenção humana.
</p>

<p>
Essencialmente, o Web Service faz com que os recursos da aplicação do software
estejam disponíveis sobre a rede de uma forma normalizada. Outras tecnologias
fazem a mesma coisa, como por exemplo, os browsers da Internet acedem às páginas
Web disponíveis usando por norma as tecnologias da Internet, HTTP e HTML. No
entanto, estas tecnologias não são bem sucedidas na comunicação e integração de
aplicações. Existe uma grande motivação sobre a tecnologia Web Service pois
possibilita que diferentes aplicações comuniquem entre si e utilizem recursos
diferentes.
</p>

<p>
Utilizando a tecnologia Web Service, uma aplicação pode invocar outra para
efectuar tarefas simples ou complexas mesmo que as duas aplicações estejam em
diferentes sistemas e escritas em linguagens diferentes. Por outras palavras, os
Web Services fazem com que os seus recursos estejam disponíveis para que
qualquer aplicação cliente possa operar e extrair os recursos fornecidos pelo
Web Service.
</p>


<ul>
	<li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/Web_service">http://pt.wikipedia.org/wiki/Web_service</a></li>
</ul>
