<h2>Ebay Finding</h2>

<ul>
	<li><a href="/rest/client">Client</a></li>
</ul>


<h3>Descrição</h3>

<p>
eBay é o nome de uma empresa de comércio eletrônico fundada nos Estados Unidos, em Setembro de 1995, por Pierre Omydiar. Atualmente é o maior site do mundo para a venda e compra de bens, é o mais popular shopping da internet, e possivelmente foi a pioneira neste tipo de trabalho.
</p>
<p>
O eBay possuía mais de 181 milhões de membros registrados em todo do mundo ao fim de 2005. O eBay tem por finalidade fornecer uma plataforma global de negociações, onde qualquer pessoa pode negociar qualquer coisa. Em 2005, o eBay gerou mais de 21 bilhões de dólares em mercadorias transacionadas.
</p>

<ul>
    <li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/EBay">http://pt.wikipedia.org/wiki/EBay</a></li>
    <li><strong>Site:</strong> <a href="http://ebay.com">http://ebay.com</a></li>
    <li><strong>Site Api:</strong> <a href="http://developer.ebay.com/DevZone/finding/CallRef/findItemsByProduct.html#Response.searchResult.item.listingInfo.bestOfferEnabled">http://developer.ebay.com/</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.service.ebay.finding.html">http://framework.zend.com/manual/en/zend.service.ebay.finding.htmli</a></li>
    <li><strong>Código:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/application/controllers/EbayfindingController.php" target="_blank">github.com</a></li>
</ul>
