<h2>ATOM</h2>

<ul>
	<li><a href="/atom/server">Server</a></li>
	<li><a href="/atom/client">Client</a></li>
</ul>

<h3>Descrição</h3>

<p>
Ao contrário do RSS, Atom não é uma sigla, mas também é um formato para ler e
escrever informações na Web. Há quem diga que esse projeto é, inicialmente, uma
proposta de unificação do RSS 1.0 e do RSS 2.0. O Atom também é baseado em XML,
mas seu desenvolvimento é tido como mais sofisticado. O grupo que nele trabalha
tem até o apoio de grandes corporações, como o Google.
</p>

<p>
Atom é o nome dado a um estilo baseado em conteúdo XML e metadados, ou seja, é
um protocolo ao nível da aplicação para publicar e editar Fontes web que são
periodicamente atualizadas, como por exemplo Blogs. Os feeds devem ser formados
em formato XML e são identificados como application/atom+xml media type. O
funcionamento deles não difere das Markup Languages tradicionais, com
cabeçalhos, títulos e corpo como no HTML 4.0.
</p>

<ul>
    <li><strong>Wiki:</strong> <a href="http://pt.wikipedia.org/wiki/Atom">http://pt.wikipedia.org/wiki/Atom</a></li>
    <li><strong>Zend Framework:</strong> <a href="http://framework.zend.com/manual/en/zend.feed.consuming-atom.html">http://framework.zend.com/manual/en/zend.feed.consuming-atom.html</a></li>
    <li><strong>Especificação:</strong> <a href="http://www.atomenabled.org/">http://www.atomenabled.org/</a></li>
    <li><strong>Código:</strong> <a href="https://github.com/zedmaster/Webservices/blob/master/application/controllers/AtomController.php" target="_blank">github.com</a></li>
</ul>
